import { CategoryItem, VideoItem } from '../types';

export const MOCK_CATEGORIES: CategoryItem[] = [
  {
    id: 'cat-scifi',
    name: 'Sci-Fi & Cyberpunk',
    slug: 'sci-fi',
    iconName: 'Rocket',
    count: 48,
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    description: 'Futuristic dystopias, interstellar travel, and artificial intelligence.',
  },
  {
    id: 'cat-action',
    name: 'Action & Adventure',
    slug: 'action',
    iconName: 'Flame',
    count: 64,
    backdrop: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    description: 'High-octane pursuits, pulse-pounding thrills, and epic quests.',
  },
  {
    id: 'cat-thriller',
    name: 'Mystery & Thriller',
    slug: 'thriller',
    iconName: 'Eye',
    count: 37,
    backdrop: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    description: 'Mind-bending psychological narratives and dark enigmas.',
  },
  {
    id: 'cat-drama',
    name: 'Prestige Drama',
    slug: 'drama',
    iconName: 'HeartHandshake',
    count: 52,
    backdrop: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=800&q=80',
    description: 'Emotionally resonant, award-winning human stories.',
  },
  {
    id: 'cat-animation',
    name: 'Animation & Anime',
    slug: 'animation',
    iconName: 'Sparkles',
    count: 41,
    backdrop: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
    description: 'Mesmerizing hand-drawn and 3D visual masterpieces.',
  },
  {
    id: 'cat-documentary',
    name: 'Documentary & Nature',
    slug: 'documentary',
    iconName: 'Globe',
    count: 29,
    backdrop: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    description: 'Real-world science, cosmos exploration, and natural wonders.',
  },
];

export const MOCK_VIDEOS: VideoItem[] = [
  {
    id: 'vid-scifi-01',
    title: 'Chronicles of the Void: Episode VI',
    description: 'In the twilight era of the solar federation, a rogue navigator discovers an artificial gateway hovering on the edge of the Kuiper belt, unleashing whispers from an ancient universe.',
    thumbnail: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80',
    backdrop: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=2560&q=85',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    embed_url: 'https://drive.google.com/file/d/1B7X4_fake_drive_id_01/preview',
    source_type: 'html5',
    type: 'series',
    genre: ['Sci-Fi', 'Space Opera', 'Adventure'],
    year: 2026,
    duration: '48m per episode',
    language: 'English (Dolby Atmos)',
    quality: '4K Ultra HD',
    rating: 9.1,
    cast: ['Elena Vance', 'Marcus Thorne', 'Aria Sterling', 'Kaelen Rios'],
    director: 'Denis Villeneuve-inspired Studio',
    featured: true,
    trending: true,
    tags: ['Space', 'Cosmic Horror', 'AI', 'Interstellar'],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Season 1: Whispers in the Dark',
        episodes: [
          {
            id: 'ep-scifi-01-01',
            episodeNumber: 1,
            seasonNumber: 1,
            title: 'Signal Beyond Ceres',
            description: 'A deep-space surveyor intercepts an anomaly emitting harmonized frequencies not seen since before the First Collapse.',
            duration: '52m',
            thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
            embed_url: 'https://drive.google.com/file/d/1B7X4_fake_drive_id_01/preview',
            source_type: 'html5',
          },
          {
            id: 'ep-scifi-01-02',
            episodeNumber: 2,
            seasonNumber: 1,
            title: 'Vector Calibration',
            description: 'As the crew approaches the coordinates, relativistic time slippage causes fragmented visions across the navigation bridge.',
            duration: '47m',
            thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
            source_type: 'html5',
          },
          {
            id: 'ep-scifi-01-03',
            episodeNumber: 3,
            seasonNumber: 1,
            title: 'The Event Horizon Event',
            description: 'Trapped between two gravitational poles, Marcus must execute an unverified orbital maneuver.',
            duration: '55m',
            thumbnail: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
            source_type: 'html5',
          },
        ],
      },
      {
        seasonNumber: 2,
        title: 'Season 2: Convergence Protocol',
        episodes: [
          {
            id: 'ep-scifi-02-01',
            episodeNumber: 1,
            seasonNumber: 2,
            title: 'Resonance Drift',
            description: 'Elena wakes up in a duplicate sector where celestial bodies appear mirrored.',
            duration: '50m',
            thumbnail: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=600&q=80',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
            source_type: 'html5',
          },
        ],
      },
    ],
  },
  {
    id: 'vid-cyber-02',
    title: 'Neon Horizon: Tokyo 2088',
    description: 'In a rain-soaked megalopolis governed by synthetic syndicates, a memory courier accepts a black-market neural implant containing memories of humanity’s forgotten origin.',
    thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80',
    backdrop: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=2560&q=85',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    source_type: 'html5',
    type: 'movie',
    genre: ['Cyberpunk', 'Action', 'Sci-Fi'],
    year: 2026,
    duration: '2h 14m',
    language: 'Japanese / English Sub',
    quality: '4K Ultra HD',
    rating: 8.8,
    cast: ['Kenji Sato', 'Ren Amamiya', 'Chiyo Takahashi', 'Viktor Vance'],
    director: 'Shinichiro Watanabe Style',
    featured: true,
    trending: true,
    tags: ['Cyberpunk', 'Synthetics', 'Noir', 'Neo-Tokyo'],
  },
  {
    id: 'vid-drive-03',
    title: 'Echoes of the Deep Forest',
    description: 'A cinematic documentary captured over three years across the untouched primeval canopies of Patagonia, revealing bioluminescent flora and unseen nocturnal rituals.',
    thumbnail: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
    backdrop: 'https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=2560&q=85',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    embed_url: 'https://drive.google.com/file/d/1xMockDriveVideoIdSampleForTesting/preview',
    source_type: 'google_drive',
    type: 'movie',
    genre: ['Documentary', 'Nature'],
    year: 2025,
    duration: '1h 38m',
    language: 'English (Original)',
    quality: 'HDR',
    rating: 9.3,
    cast: ['David Attenborough Voiceover Tribute', 'Dr. Alistair Finch'],
    director: 'Luc Jacquet',
    featured: false,
    trending: true,
    tags: ['Nature', 'Wilderness', '4K Drone', 'Patagonia'],
  },
  {
    id: 'vid-action-04',
    title: 'Vanguard: Protocol Zero',
    description: 'When an orbital defense grid falls into dissident hands, an elite kinetic strike unit is dropped covertly into an underwater fortress in the North Atlantic.',
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=2560&q=85',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    source_type: 'html5',
    type: 'movie',
    genre: ['Action', 'Thriller', 'Military'],
    year: 2026,
    duration: '2h 05m',
    language: 'English',
    quality: '1080p Full HD',
    rating: 8.4,
    cast: ['Christian Bale-esque Lead', 'Zoe Saldana Style', 'Hiroyuki Sanada'],
    director: 'Chad Stahelski',
    featured: false,
    trending: true,
    tags: ['Tactical', 'SpecOps', 'Combat', 'Thriller'],
  },
  {
    id: 'vid-drama-05',
    title: 'The Silent Symphony',
    description: 'A virtuoso concert pianist who suddenly loses her hearing begins composing in isolation using acoustic vibration transducers, uncovering an eerie harmony in urban stillness.',
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80',
    backdrop: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=2560&q=85',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    source_type: 'html5',
    type: 'movie',
    genre: ['Drama', 'Music'],
    year: 2025,
    duration: '1h 54m',
    language: 'French / English Sub',
    quality: '4K Ultra HD',
    rating: 8.9,
    cast: ['Adele Haenel Style', 'Matthias Schoenaerts', 'Celine Sciamma'],
    director: 'Todd Field',
    featured: false,
    trending: false,
    tags: ['Music', 'Emotional', 'Cannes Winner', 'Classical'],
  },
  {
    id: 'vid-anime-06',
    title: 'Spirits of the Astral Realm',
    description: 'In an alternate 1920s world where constellations descend each solar equinox as mythical guardians, an apprentice clockmaker joins a celestial pilgrimage to reset the clock of destiny.',
    thumbnail: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=1200&q=80',
    backdrop: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=2560&q=85',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    source_type: 'html5',
    type: 'series',
    genre: ['Animation', 'Fantasy', 'Adventure'],
    year: 2026,
    duration: '24m per episode',
    language: 'Japanese (Dolby 5.1)',
    quality: '4K Ultra HD',
    rating: 9.4,
    cast: ['Mamoru Miyano', 'Saori Hayami', 'Takehito Koyasu'],
    director: 'Makoto Shinkai Style',
    featured: true,
    trending: true,
    tags: ['Anime', 'Celestial', 'Ghibli Vibes', 'Mythology'],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Season 1: The Solstice Descent',
        episodes: [
          {
            id: 'ep-anime-01-01',
            episodeNumber: 1,
            seasonNumber: 1,
            title: 'The Brass Constellation',
            description: 'Kaito discovers that his grandfather’s master clockwork houses a trapped astral spirit.',
            duration: '25m',
            thumbnail: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
            source_type: 'html5',
          },
          {
            id: 'ep-anime-01-02',
            episodeNumber: 2,
            seasonNumber: 1,
            title: 'Flight across the Starlit Valley',
            description: 'Pursued by mechanical inquisitors, the duo embarks on an ethereal glider journey over glowing cloudscapes.',
            duration: '24m',
            thumbnail: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=600&q=80',
            video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
            source_type: 'html5',
          },
        ],
      },
    ],
  },
  {
    id: 'vid-thrill-07',
    title: 'The Obsidian Enigma',
    description: 'An architectural surveyor hired to examine a subterranean brutalist vault beneath the Swiss Alps discovers that the structure alters its interior blueprints every midnight.',
    thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1200&q=80',
    backdrop: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=2560&q=85',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    source_type: 'html5',
    type: 'movie',
    genre: ['Mystery', 'Thriller', 'Psychological'],
    year: 2025,
    duration: '1h 48m',
    language: 'German / English Sub',
    quality: '4K Ultra HD',
    rating: 8.7,
    cast: ['Paula Beer', 'Sebastian Koch', 'Lars Eidinger'],
    director: 'David Fincher Vibe',
    featured: false,
    trending: true,
    tags: ['Architecture', 'Brutalist', 'Puzzle', 'Suspense'],
  },
  {
    id: 'vid-scifi-08',
    title: 'Solaris Convergence',
    description: 'Sent to salvage an abandoned orbital harvester near Jupiter, an exploratory team uncovers a quantum intelligence that mirrors their deepest subconscious memories.',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    backdrop: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=2560&q=85',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    source_type: 'html5',
    type: 'movie',
    genre: ['Sci-Fi', 'Psychological'],
    year: 2026,
    duration: '2h 18m',
    language: 'English',
    quality: '4K Ultra HD',
    rating: 8.6,
    cast: ['Jessica Chastain', 'Oscar Isaac', 'Steven Yeun'],
    director: 'Alex Garland',
    featured: false,
    trending: false,
    tags: ['Jupiter', 'Quantum', 'Philosophy'],
  },
];
